# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setFixedSize(732, 660)
        Dialog.setWindowFlag(QtCore.Qt.WindowContextHelpButtonHint, False)
        Dialog.setStyleSheet("background-color: rgb(48, 48, 48);\n"
"color: rgb(239, 239, 239);")
        self.go_quick_view_pushButton = QtWidgets.QPushButton(Dialog)
        self.go_quick_view_pushButton.setGeometry(QtCore.QRect(468, 20, 121, 41))
        self.go_quick_view_pushButton.setStyleSheet("QPushButton{\n"
"    background-color: rgb(48, 48, 48);\n"
"    color: rgb(239, 239, 239);\n"
"    border: 2px solid yellow;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(55, 55, 55);\n"
"}")
        self.go_quick_view_pushButton.setObjectName("go_quick_view_pushButton")
        self.go_export_pushButton = QtWidgets.QPushButton(Dialog)
        self.go_export_pushButton.setGeometry(QtCore.QRect(590, 20, 121, 41))
        self.go_export_pushButton.setStyleSheet("QPushButton{\n"
"    background-color: rgb(85, 85, 255);\n"
"    border: 0;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.go_export_pushButton.setObjectName("go_export_pushButton")
        self.stackedWidget = QtWidgets.QStackedWidget(Dialog)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 69, 731, 791))
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.view_page = QtWidgets.QWidget()
        self.view_page.setObjectName("view_page")
        self.view_specific_radioButton = QtWidgets.QRadioButton(self.view_page)
        self.view_specific_radioButton.setGeometry(QtCore.QRect(140, 20, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.view_specific_radioButton.setFont(font)
        self.view_specific_radioButton.setObjectName("view_specific_radioButton")
        self.view_all_radioButton = QtWidgets.QRadioButton(self.view_page)
        self.view_all_radioButton.setGeometry(QtCore.QRect(10, 20, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.view_all_radioButton.setFont(font)
        self.view_all_radioButton.setObjectName("view_all_radioButton")
        self.view_specific_groupBox = QtWidgets.QGroupBox(self.view_page)
        self.view_specific_groupBox.setGeometry(QtCore.QRect(350, 20, 371, 41))
        self.view_specific_groupBox.setStyleSheet("border: 0;")
        self.view_specific_groupBox.setTitle("")
        self.view_specific_groupBox.setObjectName("view_specific_groupBox")
        self.search_by_comboBox = QtWidgets.QComboBox(self.view_specific_groupBox)
        self.search_by_comboBox.setGeometry(QtCore.QRect(-1, 0, 121, 34))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_by_comboBox.sizePolicy().hasHeightForWidth())
        self.search_by_comboBox.setSizePolicy(sizePolicy)
        self.search_by_comboBox.setMinimumSize(QtCore.QSize(0, 34))
        self.search_by_comboBox.setMaximumSize(QtCore.QSize(16777215, 34))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.search_by_comboBox.setFont(font)
        self.search_by_comboBox.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"")
        self.search_by_comboBox.setMaxVisibleItems(15)
        self.search_by_comboBox.setObjectName("search_by_comboBox")
        self.search_by_comboBox.addItem("")
        self.search_by_comboBox.addItem("")
        self.search_by_comboBox.addItem("")
        self.search_by_comboBox.addItem("")
        self.search_by_comboBox.addItem("")
        self.search_password_pushButton = QtWidgets.QPushButton(self.view_specific_groupBox)
        self.search_password_pushButton.setGeometry(QtCore.QRect(340, 0, 31, 35))
        self.search_password_pushButton.setMinimumSize(QtCore.QSize(0, 35))
        self.search_password_pushButton.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 0;\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(211, 211, 211);\n"
"}")
        self.search_password_pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/search-icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.search_password_pushButton.setIcon(icon)
        self.search_password_pushButton.setIconSize(QtCore.QSize(27, 27))
        self.search_password_pushButton.setObjectName("search_password_pushButton")
        self.search_lineEdit = QtWidgets.QLineEdit(self.view_specific_groupBox)
        self.search_lineEdit.setGeometry(QtCore.QRect(149, 0, 191, 35))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_lineEdit.sizePolicy().hasHeightForWidth())
        self.search_lineEdit.setSizePolicy(sizePolicy)
        self.search_lineEdit.setMinimumSize(QtCore.QSize(0, 35))
        self.search_lineEdit.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.search_lineEdit.setFont(font)
        self.search_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border: 0;")
        self.search_lineEdit.setText("")
        self.search_lineEdit.setObjectName("search_lineEdit")
        self.view_textBrowser = QtWidgets.QTextBrowser(self.view_page)
        self.view_textBrowser.setGeometry(QtCore.QRect(10, 70, 711, 491))
        self.view_textBrowser.setObjectName("view_textBrowser")
        self.stackedWidget.addWidget(self.view_page)
        self.export_page = QtWidgets.QWidget()
        self.export_page.setObjectName("export_page")
        self.please_choose_text = QtWidgets.QLabel(self.export_page)
        self.please_choose_text.setGeometry(QtCore.QRect(10, 30, 501, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.please_choose_text.setFont(font)
        self.please_choose_text.setObjectName("please_choose_text")
        self.every_thing_radioButton = QtWidgets.QRadioButton(self.export_page)
        self.every_thing_radioButton.setGeometry(QtCore.QRect(50, 100, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.every_thing_radioButton.setFont(font)
        self.every_thing_radioButton.setChecked(True)
        self.every_thing_radioButton.setObjectName("every_thing_radioButton")
        self.custom_radioButton = QtWidgets.QRadioButton(self.export_page)
        self.custom_radioButton.setGeometry(QtCore.QRect(50, 160, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.custom_radioButton.setFont(font)
        self.custom_radioButton.setObjectName("custom_radioButton")
        self.custom_groupBox = QtWidgets.QGroupBox(self.export_page)
        self.custom_groupBox.setGeometry(QtCore.QRect(240, 90, 451, 131))
        self.custom_groupBox.setTitle("")
        self.custom_groupBox.setObjectName("custom_groupBox")
        self.username_checkBox = QtWidgets.QCheckBox(self.custom_groupBox)
        self.username_checkBox.setGeometry(QtCore.QRect(10, 10, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.username_checkBox.setFont(font)
        self.username_checkBox.setChecked(True)
        self.username_checkBox.setObjectName("username_checkBox")
        self.email_checkBox = QtWidgets.QCheckBox(self.custom_groupBox)
        self.email_checkBox.setGeometry(QtCore.QRect(10, 40, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.email_checkBox.setFont(font)
        self.email_checkBox.setChecked(True)
        self.email_checkBox.setObjectName("email_checkBox")
        self.app_name_checkBox = QtWidgets.QCheckBox(self.custom_groupBox)
        self.app_name_checkBox.setGeometry(QtCore.QRect(10, 70, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.app_name_checkBox.setFont(font)
        self.app_name_checkBox.setChecked(True)
        self.app_name_checkBox.setObjectName("app_name_checkBox")
        self.password_checkBox = QtWidgets.QCheckBox(self.custom_groupBox)
        self.password_checkBox.setGeometry(QtCore.QRect(10, 100, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.password_checkBox.setFont(font)
        self.password_checkBox.setChecked(True)
        self.password_checkBox.setObjectName("password_checkBox")
        self.creation_date_checkBox = QtWidgets.QCheckBox(self.custom_groupBox)
        self.creation_date_checkBox.setGeometry(QtCore.QRect(150, 10, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.creation_date_checkBox.setFont(font)
        self.creation_date_checkBox.setObjectName("creation_date_checkBox")
        self.category_checkBox = QtWidgets.QCheckBox(self.custom_groupBox)
        self.category_checkBox.setGeometry(QtCore.QRect(150, 40, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.category_checkBox.setFont(font)
        self.category_checkBox.setObjectName("category_checkBox")
        self.save_date_checkBox = QtWidgets.QCheckBox(self.custom_groupBox)
        self.save_date_checkBox.setGeometry(QtCore.QRect(150, 70, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.save_date_checkBox.setFont(font)
        self.save_date_checkBox.setObjectName("save_date_checkBox")
        self.password_rate_checkBox = QtWidgets.QCheckBox(self.custom_groupBox)
        self.password_rate_checkBox.setGeometry(QtCore.QRect(310, 40, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.password_rate_checkBox.setFont(font)
        self.password_rate_checkBox.setObjectName("password_rate_checkBox")
        self.note_checkBox = QtWidgets.QCheckBox(self.custom_groupBox)
        self.note_checkBox.setGeometry(QtCore.QRect(310, 70, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.note_checkBox.setFont(font)
        self.note_checkBox.setObjectName("note_checkBox")
        self.update_date_checkBox = QtWidgets.QCheckBox(self.custom_groupBox)
        self.update_date_checkBox.setGeometry(QtCore.QRect(150, 100, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.update_date_checkBox.setFont(font)
        self.update_date_checkBox.setObjectName("update_date_checkBox")
        self.mobile_number_checkBox = QtWidgets.QCheckBox(self.custom_groupBox)
        self.mobile_number_checkBox.setGeometry(QtCore.QRect(310, 10, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.mobile_number_checkBox.setFont(font)
        self.mobile_number_checkBox.setChecked(True)
        self.mobile_number_checkBox.setObjectName("mobile_number_checkBox")
        self.line = QtWidgets.QFrame(self.export_page)
        self.line.setGeometry(QtCore.QRect(0, 270, 731, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.export_feedback = QtWidgets.QLabel(self.export_page)
        self.export_feedback.setGeometry(QtCore.QRect(150, 540, 571, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.export_feedback.setFont(font)
        self.export_feedback.setStyleSheet("color: rgb(255, 0, 0);")
        self.export_feedback.setText("")
        self.export_feedback.setObjectName("export_feedback")
        self.export_pushButton = QtWidgets.QPushButton(self.export_page)
        self.export_pushButton.setGeometry(QtCore.QRect(20, 520, 121, 44))
        self.export_pushButton.setMinimumSize(QtCore.QSize(60, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.export_pushButton.setFont(font)
        self.export_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.export_pushButton.setToolTip("")
        self.export_pushButton.setStatusTip("")
        self.export_pushButton.setWhatsThis("")
        self.export_pushButton.setAccessibleName("")
        self.export_pushButton.setAccessibleDescription("")
        self.export_pushButton.setStyleSheet("QPushButton{\n"
"    background-color: rgb(80, 161, 241);\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    background-color: rgb(84, 173, 255);\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../icons/export-icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.export_pushButton.setIcon(icon1)
        self.export_pushButton.setIconSize(QtCore.QSize(35, 35))
        self.export_pushButton.setObjectName("export_pushButton")
        self.browse_pushButton = QtWidgets.QPushButton(self.export_page)
        self.browse_pushButton.setGeometry(QtCore.QRect(640, 380, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.browse_pushButton.setFont(font)
        self.browse_pushButton.setStyleSheet("QPushButton{\n"
"    border: 0;\n"
"    background-color: rgb(194, 194, 194);\n"
"    color: rgb(43, 43, 43)\n"
"}\n"
"QPushButton:hover{\n"
"    border: 1px solid black;\n"
"    text-decoration: underline;\n"
"    background-color: rgb(229, 229, 229);\n"
"}")
        self.browse_pushButton.setObjectName("browse_pushButton")
        self.extension_label = QtWidgets.QLabel(self.export_page)
        self.extension_label.setGeometry(QtCore.QRect(220, 400, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.extension_label.setFont(font)
        self.extension_label.setObjectName("extension_label")
        self.location_lineEdit = QtWidgets.QLineEdit(self.export_page)
        self.location_lineEdit.setGeometry(QtCore.QRect(410, 390, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.location_lineEdit.setFont(font)
        self.location_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.location_lineEdit.setObjectName("location_lineEdit")
        self.fileName_lineEdit = QtWidgets.QLineEdit(self.export_page)
        self.fileName_lineEdit.setGeometry(QtCore.QRect(20, 390, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fileName_lineEdit.setFont(font)
        self.fileName_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.fileName_lineEdit.setObjectName("fileName_lineEdit")
        self.fileName_text = QtWidgets.QLabel(self.export_page)
        self.fileName_text.setGeometry(QtCore.QRect(30, 370, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.fileName_text.setFont(font)
        self.fileName_text.setObjectName("fileName_text")
        self.location_text = QtWidgets.QLabel(self.export_page)
        self.location_text.setGeometry(QtCore.QRect(420, 370, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.location_text.setFont(font)
        self.location_text.setObjectName("location_text")
        self.export_text = QtWidgets.QLabel(self.export_page)
        self.export_text.setGeometry(QtCore.QRect(70, 320, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.export_text.setFont(font)
        self.export_text.setObjectName("export_text")
        self.frame = QtWidgets.QFrame(self.export_page)
        self.frame.setGeometry(QtCore.QRect(230, 320, 311, 21))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.csv_radioButton = QtWidgets.QRadioButton(self.frame)
        self.csv_radioButton.setGeometry(QtCore.QRect(220, 0, 95, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.csv_radioButton.setFont(font)
        self.csv_radioButton.setChecked(False)
        self.csv_radioButton.setObjectName("csv_radioButton")
        self.excel_radioButton = QtWidgets.QRadioButton(self.frame)
        self.excel_radioButton.setGeometry(QtCore.QRect(110, 0, 95, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.excel_radioButton.setFont(font)
        self.excel_radioButton.setChecked(True)
        self.excel_radioButton.setObjectName("excel_radioButton")
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.stackedWidget.addWidget(self.export_page)

        self.retranslateUi(Dialog)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "View all"))
        self.go_quick_view_pushButton.setText(_translate("Dialog", "Quick View"))
        self.go_export_pushButton.setText(_translate("Dialog", "Export"))
        self.view_specific_radioButton.setText(_translate("Dialog", "View Specific"))
        self.view_all_radioButton.setText(_translate("Dialog", "View All"))
        self.search_by_comboBox.setItemText(0, _translate("Dialog", "Username"))
        self.search_by_comboBox.setItemText(1, _translate("Dialog", "E-mail"))
        self.search_by_comboBox.setItemText(2, _translate("Dialog", "App name"))
        self.search_by_comboBox.setItemText(3, _translate("Dialog", "Category"))
        self.search_by_comboBox.setItemText(4, _translate("Dialog", "Password"))
        self.please_choose_text.setText(_translate("Dialog", "Please choose what informations should include:"))
        self.every_thing_radioButton.setText(_translate("Dialog", "Everything"))
        self.custom_radioButton.setText(_translate("Dialog", "Custom"))
        self.username_checkBox.setText(_translate("Dialog", "Username"))
        self.email_checkBox.setText(_translate("Dialog", "E-mail"))
        self.app_name_checkBox.setText(_translate("Dialog", "App name"))
        self.password_checkBox.setText(_translate("Dialog", "Password"))
        self.creation_date_checkBox.setText(_translate("Dialog", "Creation Date"))
        self.category_checkBox.setText(_translate("Dialog", "Category"))
        self.save_date_checkBox.setText(_translate("Dialog", "Save date"))
        self.password_rate_checkBox.setWhatsThis(_translate("Dialog", "<html><head/><body><p><br/></p></body></html>"))
        self.password_rate_checkBox.setText(_translate("Dialog", "Pass. rate"))
        self.note_checkBox.setText(_translate("Dialog", "Note"))
        self.update_date_checkBox.setText(_translate("Dialog", "Update date"))
        self.mobile_number_checkBox.setText(_translate("Dialog", "Mobile Nb."))
        self.export_pushButton.setText(_translate("Dialog", "Export"))
        self.browse_pushButton.setText(_translate("Dialog", "Browse"))
        self.extension_label.setText(_translate("Dialog", ".xlsx"))
        self.fileName_text.setText(_translate("Dialog", "File Name:"))
        self.location_text.setText(_translate("Dialog", "Location:"))
        self.export_text.setText(_translate("Dialog", "Format:"))
        self.csv_radioButton.setText(_translate("Dialog", ".CSV"))
        self.excel_radioButton.setText(_translate("Dialog", ".xlsx"))
