# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'delete_all_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setFixedSize(561, 546)
        Dialog.setWindowFlag(QtCore.Qt.WindowContextHelpButtonHint, False)
        Dialog.setStyleSheet("background-color: rgb(48, 48, 48);\n"
"color: rgb(239, 239, 239);")
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.delete_account_steps_stackedWidget = QtWidgets.QStackedWidget(Dialog)
        self.delete_account_steps_stackedWidget.setObjectName("delete_account_steps_stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.are_you_sure_text = QtWidgets.QLabel(self.page)
        self.are_you_sure_text.setGeometry(QtCore.QRect(40, 10, 441, 211))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.are_you_sure_text.setFont(font)
        self.are_you_sure_text.setWordWrap(True)
        self.are_you_sure_text.setObjectName("are_you_sure_text")
        self.start_pushButton = QtWidgets.QPushButton(self.page)
        self.start_pushButton.setGeometry(QtCore.QRect(140, 240, 93, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_pushButton.sizePolicy().hasHeightForWidth())
        self.start_pushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.start_pushButton.setFont(font)
        self.start_pushButton.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 0, 0);\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 97, 44);\n"
"}")
        self.start_pushButton.setObjectName("start_pushButton")
        self.cancel_pushButton = QtWidgets.QPushButton(self.page)
        self.cancel_pushButton.setGeometry(QtCore.QRect(300, 240, 93, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancel_pushButton.sizePolicy().hasHeightForWidth())
        self.cancel_pushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.cancel_pushButton.setFont(font)
        self.cancel_pushButton.setStyleSheet("QPushButton{\n"
"    background-color: rgb(85, 85, 255);\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(102, 125, 255);\n"
"}")
        self.cancel_pushButton.setObjectName("cancel_pushButton")
        self.delete_account_steps_stackedWidget.addWidget(self.page)
        self.step1_page = QtWidgets.QWidget()
        self.step1_page.setObjectName("step1_page")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.step1_page)
        self.gridLayout_18.setObjectName("gridLayout_18")
        spacerItem = QtWidgets.QSpacerItem(168, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_18.addItem(spacerItem, 0, 0, 1, 1)
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setSpacing(15)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.verify_account_text = QtWidgets.QLabel(self.step1_page)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.verify_account_text.setFont(font)
        self.verify_account_text.setObjectName("verify_account_text")
        self.verticalLayout_20.addWidget(self.verify_account_text)
        self.username_lineEdit = QtWidgets.QLineEdit(self.step1_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.username_lineEdit.sizePolicy().hasHeightForWidth())
        self.username_lineEdit.setSizePolicy(sizePolicy)
        self.username_lineEdit.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.username_lineEdit.setFont(font)
        self.username_lineEdit.setStyleSheet("background-color: rgb(255,255,255);\n"
"color: rgb(0,0,0);\n"
"border: 0;")
        self.username_lineEdit.setText("")
        self.username_lineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.username_lineEdit.setObjectName("username_lineEdit")
        self.verticalLayout_20.addWidget(self.username_lineEdit)
        self.password_lineEdit = QtWidgets.QLineEdit(self.step1_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.password_lineEdit.sizePolicy().hasHeightForWidth())
        self.password_lineEdit.setSizePolicy(sizePolicy)
        self.password_lineEdit.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.password_lineEdit.setFont(font)
        self.password_lineEdit.setStyleSheet("background-color: rgb(255,255,255);\n"
"color: rgb(0,0,0);\n"
"border: 0;")
        self.password_lineEdit.setText("")
        self.password_lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_lineEdit.setObjectName("password_lineEdit")
        self.verticalLayout_20.addWidget(self.password_lineEdit)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem1)
        self.step1_check_pushButton = QtWidgets.QPushButton(self.step1_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.step1_check_pushButton.sizePolicy().hasHeightForWidth())
        self.step1_check_pushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.step1_check_pushButton.setFont(font)
        self.step1_check_pushButton.setStyleSheet("QPushButton{\n"
"    background-color: rgb(171, 171, 171);\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(232, 232, 232);\n"
"}")
        self.step1_check_pushButton.setObjectName("step1_check_pushButton")
        self.horizontalLayout_19.addWidget(self.step1_check_pushButton)
        self.verticalLayout_20.addLayout(self.horizontalLayout_19)
        self.step1_feedback = QtWidgets.QLabel(self.step1_page)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.step1_feedback.setFont(font)
        self.step1_feedback.setStyleSheet("color: rgb(255, 60, 60);")
        self.step1_feedback.setText("")
        self.step1_feedback.setWordWrap(True)
        self.step1_feedback.setObjectName("step1_feedback")
        self.verticalLayout_20.addWidget(self.step1_feedback)
        self.gridLayout_18.addLayout(self.verticalLayout_20, 0, 1, 2, 1)
        spacerItem2 = QtWidgets.QSpacerItem(314, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_18.addItem(spacerItem2, 2, 1, 1, 1)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem3)
        self.verticalLayout_21 = QtWidgets.QVBoxLayout()
        self.verticalLayout_21.setSpacing(12)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.step1_text = QtWidgets.QLabel(self.step1_page)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.step1_text.setFont(font)
        self.step1_text.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.step1_text.setObjectName("step1_text")
        self.verticalLayout_21.addWidget(self.step1_text)
        self.next_step_pushButton = QtWidgets.QPushButton(self.step1_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.next_step_pushButton.sizePolicy().hasHeightForWidth())
        self.next_step_pushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.next_step_pushButton.setFont(font)
        self.next_step_pushButton.setStyleSheet("QPushButton{\n"
"    background-color: rgb(171, 171, 171);\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(232, 232, 232);\n"
"}")
        self.next_step_pushButton.setObjectName("next_step_pushButton")
        self.verticalLayout_21.addWidget(self.next_step_pushButton)
        self.horizontalLayout_20.addLayout(self.verticalLayout_21)
        self.gridLayout_18.addLayout(self.horizontalLayout_20, 2, 2, 1, 1)
        self.delete_account_steps_stackedWidget.addWidget(self.step1_page)
        self.step2_page = QtWidgets.QWidget()
        self.step2_page.setObjectName("step2_page")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.step2_page)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout()
        self.verticalLayout_24.setSpacing(20)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.step2_attention_label = QtWidgets.QLabel(self.step2_page)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.step2_attention_label.setFont(font)
        self.step2_attention_label.setWordWrap(True)
        self.step2_attention_label.setObjectName("step2_attention_label")
        self.verticalLayout_24.addWidget(self.step2_attention_label)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem4)
        self.step2_agree_checkBox = QtWidgets.QCheckBox(self.step2_page)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.step2_agree_checkBox.setFont(font)
        self.step2_agree_checkBox.setObjectName("step2_agree_checkBox")
        self.horizontalLayout_24.addWidget(self.step2_agree_checkBox)
        self.verticalLayout_24.addLayout(self.horizontalLayout_24)
        self.gridLayout_19.addLayout(self.verticalLayout_24, 0, 0, 1, 2)
        spacerItem5 = QtWidgets.QSpacerItem(20, 373, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_19.addItem(spacerItem5, 1, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(329, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_19.addItem(spacerItem6, 2, 0, 1, 1)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem7)
        self.verticalLayout_23 = QtWidgets.QVBoxLayout()
        self.verticalLayout_23.setSpacing(12)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.step2_text = QtWidgets.QLabel(self.step2_page)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.step2_text.setFont(font)
        self.step2_text.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.step2_text.setObjectName("step2_text")
        self.verticalLayout_23.addWidget(self.step2_text)
        self.next_step_pushButton_2 = QtWidgets.QPushButton(self.step2_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.next_step_pushButton_2.sizePolicy().hasHeightForWidth())
        self.next_step_pushButton_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.next_step_pushButton_2.setFont(font)
        self.next_step_pushButton_2.setStyleSheet("QPushButton{\n"
"    background-color: rgb(171, 171, 171);\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(232, 232, 232);\n"
"}")
        self.next_step_pushButton_2.setObjectName("next_step_pushButton_2")
        self.verticalLayout_23.addWidget(self.next_step_pushButton_2)
        self.horizontalLayout_23.addLayout(self.verticalLayout_23)
        self.gridLayout_19.addLayout(self.horizontalLayout_23, 2, 1, 1, 1)
        self.delete_account_steps_stackedWidget.addWidget(self.step2_page)
        self.step3_page = QtWidgets.QWidget()
        self.step3_page.setObjectName("step3_page")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.step3_page)
        self.gridLayout_20.setObjectName("gridLayout_20")
        spacerItem8 = QtWidgets.QSpacerItem(412, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_20.addItem(spacerItem8, 2, 1, 1, 1)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem9)
        self.verticalLayout_25 = QtWidgets.QVBoxLayout()
        self.verticalLayout_25.setSpacing(12)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.step3_text = QtWidgets.QLabel(self.step3_page)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.step3_text.setFont(font)
        self.step3_text.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.step3_text.setObjectName("step3_text")
        self.verticalLayout_25.addWidget(self.step3_text)
        self.horizontalLayout_25.addLayout(self.verticalLayout_25)
        self.gridLayout_20.addLayout(self.horizontalLayout_25, 2, 3, 1, 2)
        spacerItem10 = QtWidgets.QSpacerItem(48, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_20.addItem(spacerItem10, 0, 0, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(20, 410, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_20.addItem(spacerItem11, 1, 2, 1, 1)
        self.verticalLayout_26 = QtWidgets.QVBoxLayout()
        self.verticalLayout_26.setContentsMargins(-1, 30, -1, -1)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.write_text = QtWidgets.QLabel(self.step3_page)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.write_text.setFont(font)
        self.write_text.setObjectName("write_text")
        self.verticalLayout_26.addWidget(self.write_text)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setContentsMargins(-1, 10, -1, -1)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem12)
        self.specific_text_lineEdit = QtWidgets.QLineEdit(self.step3_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.specific_text_lineEdit.sizePolicy().hasHeightForWidth())
        self.specific_text_lineEdit.setSizePolicy(sizePolicy)
        self.specific_text_lineEdit.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.specific_text_lineEdit.setFont(font)
        self.specific_text_lineEdit.setStyleSheet("background-color: rgb(255,255,255);\n"
"color: rgb(0,0,0);\n"
"border: 0;")
        self.specific_text_lineEdit.setText("")
        self.specific_text_lineEdit.setMaxLength(14)
        self.specific_text_lineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.specific_text_lineEdit.setPlaceholderText("")
        self.specific_text_lineEdit.setObjectName("specific_text_lineEdit")
        self.horizontalLayout_26.addWidget(self.specific_text_lineEdit)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem13)
        self.verticalLayout_26.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setContentsMargins(-1, 8, -1, -1)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem14)
        self.step3_confirm_pushButton = QtWidgets.QPushButton(self.step3_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.step3_confirm_pushButton.sizePolicy().hasHeightForWidth())
        self.step3_confirm_pushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.step3_confirm_pushButton.setFont(font)
        self.step3_confirm_pushButton.setStyleSheet("QPushButton{\n"
"    background-color: rgb(171, 171, 171);\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(232, 232, 232);\n"
"}")
        self.step3_confirm_pushButton.setObjectName("step3_confirm_pushButton")
        self.horizontalLayout_27.addWidget(self.step3_confirm_pushButton)
        self.verticalLayout_26.addLayout(self.horizontalLayout_27)
        self.gridLayout_20.addLayout(self.verticalLayout_26, 0, 1, 1, 3)
        spacerItem15 = QtWidgets.QSpacerItem(152, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_20.addItem(spacerItem15, 0, 4, 1, 1)
        self.delete_account_steps_stackedWidget.addWidget(self.step3_page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.end_text = QtWidgets.QLabel(self.page_2)
        self.end_text.setGeometry(QtCore.QRect(40, 0, 461, 211))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.end_text.setFont(font)
        self.end_text.setWordWrap(True)
        self.end_text.setObjectName("end_text")
        self.go_back_pushButton = QtWidgets.QPushButton(self.page_2)
        self.go_back_pushButton.setGeometry(QtCore.QRect(420, 290, 101, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.go_back_pushButton.sizePolicy().hasHeightForWidth())
        self.go_back_pushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.go_back_pushButton.setFont(font)
        self.go_back_pushButton.setStyleSheet("QPushButton{\n"
"    background-color: rgb(85, 85, 255);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(102, 125, 255);\n"
"}")
        self.go_back_pushButton.setObjectName("go_back_pushButton")
        self.delete_account_steps_stackedWidget.addWidget(self.page_2)
        self.gridLayout.addWidget(self.delete_account_steps_stackedWidget, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.delete_account_steps_stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Clear all Passwords"))
        self.are_you_sure_text.setText(_translate("Dialog", "You are Going to delete all your saved Passwords! \n"
"Are you sure?"))
        self.start_pushButton.setText(_translate("Dialog", "Start"))
        self.cancel_pushButton.setText(_translate("Dialog", "Cancel"))
        self.verify_account_text.setText(_translate("Dialog", "Please verify your account:"))
        self.username_lineEdit.setPlaceholderText(_translate("Dialog", "Username..."))
        self.password_lineEdit.setPlaceholderText(_translate("Dialog", "Password..."))
        self.step1_check_pushButton.setText(_translate("Dialog", "Check"))
        self.step1_text.setText(_translate("Dialog", "Step 1/3:"))
        self.next_step_pushButton.setText(_translate("Dialog", "Next"))
        self.step2_attention_label.setText(_translate("Dialog", "Please note that this operation will due to lose all your data(apps and password) and all your personal account data."))
        self.step2_agree_checkBox.setText(_translate("Dialog", "Agree"))
        self.step2_text.setText(_translate("Dialog", "Step 2/3:"))
        self.next_step_pushButton_2.setText(_translate("Dialog", "Next"))
        self.step3_text.setText(_translate("Dialog", "Step 3/3:"))
        self.write_text.setText(_translate("Dialog", "Please Write \"Delete all\" below..."))
        self.step3_confirm_pushButton.setText(_translate("Dialog", "confirm..."))
        self.end_text.setText(_translate("Dialog", "Operation successfuly Done..."))
        self.go_back_pushButton.setText(_translate("Dialog", "Go back"))
